name: "chatbot"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks:
      - net

  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    networks:
      - net

  server:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - "./backend:/app"
    env_file:
      - path: ./backend/.env
    depends_on:
      - mongodb
      - chroma
    networks:
      - net

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    env_file:
      - path: ./client/.env
    depends_on:
      - server
    networks:
      - net
  
volumes:
  redis:
  mongo:

networks:
 net:
  driver: bridge